### PR TITLE
Replaced 'dom-to-image' with 'dom-to-image-more' library

### PR DESCRIPTION
**Pull request by sandeepB3**
### Issue: #76 
**_Replaced the 'dom-to-image' with 'dom-to-image-more' library in --> client/js/helpers/shareCard.js_** <br>
The 'dom-to-image-more' library is primarily based on dom-to-image with some bugs fixes and some new features. Hence the code remains the same, only the library is changed.

### CODE REVIEW

**Comment by bacloud23** [comment]
hi thanks!
without proper installation and tests I do not merge

**Comment by sandeepB3** [comment]
**Thanks for the quick reply!**   

**I have done the proper installations but when I try to run the server.js file I am facing this error:**   
Screenshot 2022-10-02 at 1 31 29 AM
#### Could you please help me with this, or could you please post instructions on how to run the application.

**Comment by bacloud23** [comment]
ok, I guess you didn't fulfill .env file .

**Comment by sandeepB3** [comment]
Okay got it. Thanks.  
will get back to you

**Comment by bacloud23** [comment]
@sandeepB3 any follow up?
actually I do remember sharing also is only possible on phone devices as a feature. you should emulate that as well using Chrome browser

**Comment by sandeepB3** [comment]
Hey!!       
I even fulfilled the .env files yet I am facing the same problem. 
WhatsApp Image 2022-10-03 at 12 24 22 AM

Yet I am facing the same problem :(
All my API keys are working I have tested them separately.

**Comment by sandeepB3** [comment]
Is there any specific step for honeypot API that I may have missed?   
I have worked with openweather and google maps before. So I am confident about them. 
Not sure about honeypot tho

**Comment by bacloud23** [comment]
NODE-ENV

must be either localhost or production

**Comment by bacloud23** [comment]
@sandeepB3 any follow up ? 
thanks

**Comment by sandeepB3** [comment]
Hey!! Sorry my mid semester exams are approaching so couldn't give much time to os contributions.

**Pull request closed without merging**
